language: python
python:
  - "3.6"
services:
  - postgresql

install:
  - cd API_Enhanced_City
  - export PYTHONPATH=$PYTHONPATH:.
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database extendeddoc;' -U postgres
  - psql -c '\l' -U postgres

jobs:
  include:
    - stage: Tests
      install:
        - pip install -e .
        - pip install pytest pytest-benchmark
      script:
        - pwd
        - pytest -s
#    - stage: "Markdown link checks"
#      language: node_js
#      node_js: 12
#      script:
#        - npm install --global remark-cli remark-validate-links
#        - remark -u validate-links .
#        - |
#          export FAILURE_THRESHOLD=1
#          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
#          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
#            exit 1;
#          fi
